export const STATIC_MENU_ITEMS = [
  {
    id: 'regular-single',
    name: '1 Regular Pizza (Single Topping)',
    description: 'Toppings shown: Onion, Capsicum, Tomato, Corn',
    category: 'Regular Pizza',
    image: '/images/spring_feast.jpg',
    price: 81,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'regular-single-drink',
    name: '1 Regular Pizza (Single Topping) + Soft Drink',
    description: 'Includes a chilled soft drink',
    category: 'Regular Pizza',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=600&auto=format&fit=crop',
    price: 101,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'regular-double',
    name: '1 Regular Pizza (Double Topping)',
    description: 'Toppings shown: Onion, Capsicum, Tomato, Corn',
    category: 'Regular Pizza',
    image: '/images/spring_feast.jpg',
    price: 91,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'regular-double-drink',
    name: '1 Regular Pizza (Double Topping) + Soft Drink',
    description: 'Includes a chilled soft drink',
    category: 'Regular Pizza',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=600&auto=format&fit=crop',
    price: 111,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'combo-single',
    name: '2 Regular Pizzas (Single Topping)',
    description: 'Toppings shown: Onion, Capsicum, Tomato, Corn',
    category: 'Combo Pizzas',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=600&auto=format&fit=crop',
    price: 162,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'combo-double',
    name: '2 Regular Pizzas (Double Topping)',
    description: 'Toppings shown: Onion, Capsicum, Tomato, Corn',
    category: 'Combo Pizzas',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=600&auto=format&fit=crop',
    price: 183,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'combo-double-drink',
    name: '2 Regular Pizzas (Double Topping) + Soft Drink',
    description: 'Includes a chilled soft drink',
    category: 'Combo Pizzas',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=600&auto=format&fit=crop',
    price: 203,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'party-4-single',
    name: '4 Regular Pizzas (Single Topping)',
    description: 'Party pack for friends and family',
    category: 'Party Packs',
    image: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?q=80&w=600&auto=format&fit=crop',
    price: 305,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'party-4-double',
    name: '4 Regular Pizzas (Double Topping)',
    description: 'Party pack for friends and family',
    category: 'Party Packs',
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?q=80&w=600&auto=format&fit=crop',
    price: 336,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'party-6-single',
    name: '6 Regular Pizzas (Single Topping)',
    description: 'Large party pack',
    category: 'Party Packs',
    image: '/images/spring_feast.jpg',
    price: 459,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'party-6-double',
    name: '6 Regular Pizzas (Double Topping)',
    description: 'Large party pack',
    category: 'Party Packs',
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=600&auto=format&fit=crop',
    price: 499,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'party-8-single',
    name: '8 Regular Pizzas (Single Topping)',
    description: 'Family feast pack',
    category: 'Party Packs',
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?q=80&w=600&auto=format&fit=crop',
    price: 611,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'party-8-double',
    name: '8 Regular Pizzas (Double Topping)',
    description: 'Family feast pack',
    category: 'Party Packs',
    image: 'https://images.unsplash.com/photo-1506280754576-f6fa8a873550?q=80&w=600&auto=format&fit=crop',
    price: 673,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'party-10-single',
    name: '10 Regular Pizzas (Single Topping)',
    description: 'Big party pack',
    category: 'Party Packs',
    image: 'https://images.unsplash.com/photo-1576458088443-04a19bb13da6?q=80&w=600&auto=format&fit=crop',
    price: 754,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'party-10-double',
    name: '10 Regular Pizzas (Double Topping)',
    description: 'Big party pack',
    category: 'Party Packs',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=600&auto=format&fit=crop',
    price: 846,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'burger-aloo',
    name: '2 Aloo Tikki Burgers',
    description: 'Veg burger duo',
    category: 'Burgers & Sandwiches',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=600&auto=format&fit=crop',
    price: 101,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'sandwich-jumbo',
    name: '2 Jumbo Sandwiches',
    description: 'Veg jumbo sandwiches',
    category: 'Burgers & Sandwiches',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=600&auto=format&fit=crop',
    price: 112,
    isVeg: true,
    customizable: false,
    orderable: true
  },
  {
    id: 'mojito-ocean',
    name: 'Ocean Blue Mojito',
    description: 'Refreshing mocktail flavour',
    category: 'Mojito Flavours',
    image: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?q=80&w=600&auto=format&fit=crop',
    price: null,
    isVeg: true,
    customizable: false,
    orderable: false
  },
  {
    id: 'mojito-mint',
    name: 'Mint Mojito',
    description: 'Cool mint refreshment',
    category: 'Mojito Flavours',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=600&auto=format&fit=crop',
    price: null,
    isVeg: true,
    customizable: false,
    orderable: false
  },
  {
    id: 'mojito-bubble-gum',
    name: 'Bubble Gum Mojito',
    description: 'Fun sweet flavour',
    category: 'Mojito Flavours',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?q=80&w=600&auto=format&fit=crop',
    price: null,
    isVeg: true,
    customizable: false,
    orderable: false
  },
  {
    id: 'mojito-blueberry',
    name: 'Blueberry Mojito',
    description: 'Berry refreshment',
    category: 'Mojito Flavours',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=600&auto=format&fit=crop',
    price: null,
    isVeg: true,
    customizable: false,
    orderable: false
  },
  {
    id: 'mojito-green-apple',
    name: 'Green Apple Mojito',
    description: 'Zesty green apple flavour',
    category: 'Mojito Flavours',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?q=80&w=600&auto=format&fit=crop',
    price: null,
    isVeg: true,
    customizable: false,
    orderable: false
  }
];
